[package]
name = "home"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"
authors = ["Teddy Byron <ted@tedbyron.com>"]
repository = "https://github.com/tedbyron/home"

[dependencies]
anyhow = "1.0.57"
axum = "0.5.7"
serde = { version = "1.0.137", features = ["derive"] }
tokio = { version = "1.19.2", features = ["rt-multi-thread", "macros", "signal", "parking_lot"] }
toml = "0.5.9"
