name = "home"
main = "packages/worker/build/worker/shim.mjs"
workers_dev = true
compatibility_date = "2022-06-19"

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
command = "pnpm -w build"

[site]
bucket = "packages/website/public"
