name = "home"
main = "packages/worker/build/worker/shim.mjs"
workers_dev = true
compatibility_date = "2022-06-19"

kv_namespaces = [
  { binding = "home-website_preview", id = "", preview_id = "b1d76fb78840473db2e3823e72b81d14" }
]

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
command = "pnpm -w build"

[site]
bucket = "packages/website/build"
